version: '3.3'
services:
  jumpstarter:
    build: .
    network_mode: host
    volumes:
      - ~/.ssh/:/root/.ssh/
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    environment:
      - GIT_CLUSTER="git@github.com:trumandk/cluster.git"
      - JUMPSTARTER_USERNAME=admin
      - JUMPSTARTER_PASSWORD=123
